In [10]:
from statsmodels.api import datasets

In [11]:
iris=datasets.get_rdataset("iris")
iris.data

D:\anconda\lib\site-packages\statsmodels\datasets\utils.py:192: FutureWarning: `item` has been deprecated and will be removed in a future version
  return dataset_meta["Title"].item()


Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [12]:
iris.data.columns=["Sepal_length","Sepal_width","Petal_length","Petal_width","Species"]

In [13]:
iris.data

Sepal_length  Sepal_width  Petal_length  Petal_width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [14]:
iris

<class 'statsmodels.datasets.utils.Dataset'>

In [15]:
iris.data.dtypes

Sepal_length    float64
Sepal_width     float64
Petal_length    float64
Petal_width     float64
Species          object
dtype: object

In [16]:
iris.data["count"]=1
iris.data

Sepal_length  Sepal_width  Petal_length  Petal_width    Species  count
0             5.1          3.5           1.4          0.2     setosa      1
1             4.9          3.0           1.4          0.2     setosa      1
2             4.7          3.2           1.3          0.2     setosa      1
3             4.6          3.1           1.5          0.2     setosa      1
4             5.0          3.6           1.4          0.2     setosa      1
..            ...          ...           ...          ...        ...    ...
145           6.7          3.0           5.2          2.3  virginica      1
146           6.3          2.5           5.0          1.9  virginica      1
147           6.5          3.0           5.2          2.0  virginica      1
148           6.2          3.4           5.4          2.3  virginica      1
149           5.9          3.0           5.1          1.8  virginica      1

[150 rows x 6 columns]

In [17]:
iris.data[["Species","count"]].groupby("Species").count()

count
Species          
setosa         50
versicolor     50
virginica      50

In [18]:
def plot_iris(iris,col1,col2):
    
    import seaborn as sns
    import matplotlib.pyplot as plt
    
    sns.lmplot(x=col1, y=col2,
              data=iris,
              hue="Species",
              fit_reg=False)
    plt.xlabel(col1)
    plt.ylabel(col2)
    
    plt.title("Iris Species")
    plt.show()

In [19]:
plot_iris(iris.data,"Petal_width","Sepal_length")
plot_iris(iris.data,"Sepal_width","Sepal_length")

<Figure size 617.75x500 with 1 Axes>

<Figure size 617.75x500 with 1 Axes>

In [20]:
from sklearn.preprocessing import scale
import pandas as pd

In [21]:
colnames=["Sepal_length","Sepal_width","Petal_length","Petal_width"]

In [22]:
iris_scaled=scale(iris.data[colnames])
iris_scaled

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [23]:
iris_scaled=pd.DataFrame(iris_scaled,columns=colnames)
print(iris_scaled)

     Sepal_length  Sepal_width  Petal_length  Petal_width
0       -0.900681     1.019004     -1.340227    -1.315444
1       -1.143017    -0.131979     -1.340227    -1.315444
2       -1.385353     0.328414     -1.397064    -1.315444
3       -1.506521     0.098217     -1.283389    -1.315444
4       -1.021849     1.249201     -1.340227    -1.315444
..            ...          ...           ...          ...
145      1.038005    -0.131979      0.819596     1.448832
146      0.553333    -1.282963      0.705921     0.922303
147      0.795669    -0.131979      0.819596     1.053935
148      0.432165     0.788808      0.933271     1.448832
149      0.068662    -0.131979      0.762758     0.790671

[150 rows x 4 columns]


In [24]:
print(iris_scaled.describe().round())

       Sepal_length  Sepal_width  Petal_length  Petal_width
count         150.0        150.0         150.0        150.0
mean           -0.0         -0.0          -0.0         -0.0
std             1.0          1.0           1.0          1.0
min            -2.0         -2.0          -2.0         -1.0
25%            -1.0         -1.0          -1.0         -1.0
50%            -0.0         -0.0           0.0          0.0
75%             1.0          1.0           1.0          1.0
max             2.0          3.0           2.0          2.0


# Normalization


In [25]:
levels={"setosa":0,"versicolor":1,"virginica":2}

In [26]:
levels["versicolor"]

1

In [27]:
[levels[x] for x in iris.data["Species"]]

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2]

In [28]:
iris.data.tail()

Sepal_length  Sepal_width  Petal_length  Petal_width    Species  count
145           6.7          3.0           5.2          2.3  virginica      1
146           6.3          2.5           5.0          1.9  virginica      1
147           6.5          3.0           5.2          2.0  virginica      1
148           6.2          3.4           5.4          2.3  virginica      1
149           5.9          3.0           5.1          1.8  virginica      1

In [29]:
type(iris_scaled)

pandas.core.frame.DataFrame

# Splitting the data into Training and testing set

In [30]:
from sklearn.model_selection import train_test_split
import numpy as np

In [31]:
np.random.seed(123)

In [32]:
m=np.asmatrix(iris_scaled)
m

matrix([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
         -1.31544430e+00],
        [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
         -1.31544430e+00],
        [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
         -1.31544430e+00],
        [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
         -1.31544430e+00],
        [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
         -1.31544430e+00],
        [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
         -1.05217993e+00],
        [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
         -1.18381211e+00],
        [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
         -1.31544430e+00],
        [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
         -1.31544430e+00],
        [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
         -1.44707648e+00],
        [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
         -1.31544430e+00],
        [-1.26418478e+00,  7.88807586e-01, 

In [33]:
iris_split=train_test_split(m,test_size=75)

In [34]:
iris_split

[matrix([[ 5.53333275e-01,  5.58610819e-01,  5.35408562e-01,
           5.27406285e-01],
         [ 1.40150837e+00,  3.28414053e-01,  5.35408562e-01,
           2.64141916e-01],
         [-1.02184904e+00, -1.31979479e-01, -1.22655167e+00,
          -1.31544430e+00],
         [ 6.74501145e-01, -5.92373012e-01,  1.04694540e+00,
           1.18556721e+00],
         [ 5.53333275e-01, -1.28296331e+00,  7.05920842e-01,
           9.22302838e-01],
         [-1.02184904e+00,  1.01900435e+00, -1.22655167e+00,
          -7.88915558e-01],
         [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
          -1.31544430e+00],
         [ 3.10997534e-01, -5.92373012e-01,  1.37546573e-01,
           1.32509732e-01],
         [ 7.95669016e-01, -5.92373012e-01,  4.78571135e-01,
           3.95774101e-01],
         [ 5.53333275e-01,  5.58610819e-01,  1.27429511e+00,
           1.71209594e+00],
         [-5.25060772e-02,  2.16998818e+00, -1.45390138e+00,
          -1.31544430e+00],
         [-1.50652052

In [35]:
np.ravel(iris_split[1][:4])

array([ 0.55333328, -1.28296331,  0.64908342,  0.3957741 ,  1.15917263,
       -0.13197948,  0.99010798,  1.18556721,  0.67450115, -0.59237301,
        1.0469454 ,  1.31719939, -0.29484182, -0.13197948,  0.194384  ,
        0.13250973])

In [36]:
X_train=iris_split[0][::4,]
Y_train=np.ravel(iris_split[0][:4])

In [37]:
X_test=iris_split[1][::4,]
Y_test=np.ravel(iris_split[1][::4,])

In [38]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(19, 4)
(16,)
(19, 4)
(76,)


In [39]:
from sklearn.neighbors import KNeighborsClassifier

In [40]:
KNN_Mod=KNeighborsClassifier(n_neighbors=15)

In [41]:
KNN_Mod.fit(X_train,Y_train)

ValueError: Found input variables with inconsistent numbers of samples: [19, 16]

In [42]:
iris_test=pd.DataFrame(X_test,columns=colnames)
iris_test

Sepal_length  Sepal_width  Petal_length  Petal_width
0       0.553333    -1.282963      0.649083     0.395774
1      -1.143017     1.249201     -1.340227    -1.447076
2      -1.748856    -0.362176     -1.340227    -1.315444
3      -0.779513    -0.822570      0.080709     0.264142
4      -0.416010     1.019004     -1.397064    -1.315444
5      -0.779513     0.788808     -1.340227    -1.315444
6      -0.900681     1.709595     -1.226552    -1.315444
7       2.249683     1.709595      1.672157     1.317199
8      -1.385353     0.328414     -1.226552    -1.315444
9       2.492019     1.709595      1.501645     1.053935
10     -1.021849    -2.433947     -0.146641    -0.262387
11     -0.052506    -0.822570      0.762758     0.922303
12     -0.900681     1.709595     -1.283389    -1.183812
13     -1.143017     0.098217     -1.283389    -1.447076
14     -0.173674    -1.052767     -0.146641    -0.262387
15     -1.627688    -1.743357     -1.397064    -1.183812
16     -1.264185     0.788808     -1.226552    -1.315444
17      2.249683    -1.052767      1.785832     1.448832
18      0.068662    -0.131979      0.762758     0.790671

In [43]:
iris_test["predicted"]=KNN_Mod.predict(X_test)
iris_test

NotFittedError: This KNeighborsClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

In [44]:
iris_test["correct"]=[1 if x==z else 0 for \
                    x,z in zip(iris_test["predicted"],Y_test)]

KeyError: 'predicted'