In [9]:
import numpy as np
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [10]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [38]:
np.random.seed(0) 

In [39]:
x1 = np.random.randint(10, size=6) # One-dimensional array

In [40]:
x1

array([5, 0, 3, 3, 7, 9])

In [41]:
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array

In [42]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [43]:
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [44]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])